info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  # 主题的CDN地址。如需启用CDN，请在主目录的config中设置，详见文档。
  cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-xaoxuu@19.5/

site_description: ""

services:
  cdn: true
